set guioptions=agit
syntax on
colorscheme darkblue
set colorcolumn=72
set number
" set cursorline
set lines=50
set columns=100
set gfn=DejaVu\ Sans\ Mono\ Book\ 12
set vb t_vb= "no bell or visual bell
