let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:loaded_matchparen = 1
let g:netrw_list_hide= '\(^\|\s\s\)\zs\.[^\.]\S\+,\~$,^\.\/$,\.pyc$'
let g:netrw_banner=0
let g:netrw_cursor=0

" disable alternate screen for vim
" http://shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=

execute pathogen#infect()

let g:NERDTreeMinimalUI=1
let g:NERDTreeWinSize = 25
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 0
let g:airline_left_sep = ' '
let g:airline_right_sep = ''
let g:airline_left_alt_sep = ' '
let g:airline_right_alt_sep = ''

set backupdir=~/local/tmp
set directory=~/local/tmp
set backup

set t_Co=256
set mouse=a
set ttymouse=xterm2
set background=dark
syntax on

" http://stevelosh.com/blog/2010/09/coming-home-to-vim/#aesthetics
set list
set listchars=tab:▸\ ,eol:¬
set nowrap
set textwidth=0
" set colorcolumn=80
" set cursorline
" set cursorcolumn
set number
set nocompatible
set hlsearch
set vb t_vb= "no bell or visual bell
" set clipboard+=unnamed

set nocindent

filetype plugin indent on
filetype plugin indent off
filetype plugin on
set autoindent
set nosmartindent
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set ruler
set showcmd
set showmode
set laststatus=2

" allow to switch away from unsaved buffers without saving OR
" discarding changes
set hidden

" http://www.guyrutenberg.com/2013/09/23/quickly-exiting-insert-mode-in-vim/
inoremap kj <ESC>
inoremap ,w <ESC>:w<Enter>
nmap ; :
let mapleader = ","
map <Leader>w :w<Enter>
" http://vim.wikia.com/wiki/Display_line_numbers
map <Leader>n :set invnumber<Enter>
" map <Leader>n :set invrelativenumber<Enter>

map <Leader>e :e .<Enter>
map <Leader>E :tabe .<Enter>
map <Leader>t :NERDTreeToggle .<Enter>
map <Leader>s :silent ! tmux send -t 'hack1:test.0' up enter<Enter>

nnoremap <C-p> :CommandT <Enter>
