$HOME/etc/scripts/initxkb
xset r rate 185 130

[ ! $SSH_AGENT_PID ] && eval `ssh-agent -s`

if [ -x /usr/lib/ssh/x11-ssh-askpass ]; then
    # Debian, Arch
    SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass
elif [ -x /usr/libexec/openssh/x11-ssh-askpass ]; then
    # Fedora
    SSH_ASKPASS=/usr/libexec/openssh/x11-ssh-askpass
else
    unset SSH_ASKPASS
fi

[ $SSH_ASKPASS ] && ssh-add < /dev/null

if [ -x /usr/bin/lxpolkit ]; then
    # lxpolkit for Arch
    /usr/bin/lxpolkit &
elif [ -x /usr/libexec/lxpolkit ]; then
    # lxpolkit for Fedora
    /usr/libexec/lxpolkit &
elif [ -x /usr/lib/x86_64-linux-gnu/lxpolkit ]; then
    # lxpolkit for Debian 64 bit
    /usr/lib/x86_64-linux-gnu/lxpolkit &
fi

urxvtd -q -f -o

xsetroot -solid "#18254A"
xrandr --dpi 96

[ -x $HOME/.wallpaper ] && $HOME/.wallpaper
[ -x $HOME/.xinitrc.local ] && $HOME/.xinitrc.local
[ -e $HOME/.Xresources ] && xrdb $HOME/.Xresources
[ -e $HOME/.Xresources.local ] && xrdb -override $HOME/.Xresources.local

exec openbox
