# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
unsetopt beep notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/zebdeos/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Source .profile is not in X11 (display manager sources automatically
# if we are in X11, so we don't want to run it twice); .profile sets
# up our home directory bin paths
[ -z "$DISPLAY" ] && source $HOME/.profile

zstyle ':completion:*' menu select
autoload -U colors && colors
#autoload -U promptinit && promptinit && prompt redhat
precmd() {
    local currtime
    currtime=$(date +'%Y-%m-%d %H:%M')
    PROMPT="%{$fg_bold[blue]%}[%n@%m%{$reset_color%} %{$fg_bold[green]%}%1~%{$reset_color%}%{$fg_bold[blue]%}]%(#.#.$)%{$reset_color%} "
    RPROMPT="%{$fg_no_bold[blue]%}($currtime)%{$reset_color%}"
}

# for the likes of gnome-terminal and mate-terminal
[ "x$TERM" = "xxterm" ] && export TERM="xterm-256color"

# per http://guides.rubygems.org/faqs/#user-install
if which ruby 1>/dev/null 2>&1 && which gem 1>/dev/null 2>&1; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"

    # We have to set $GEM_HOME to ensure Bundler doesn't disrespect
    # our system ruby if it can get sudo privileges, since it will use
    # sudo without asking first to install things system wide by default
    # (as of version 1.9). See
    #    - https://github.com/bundler/bundler/issues/3006
    #    - https://github.com/bundler/bundler/issues/2565#issuecomment-87121045
    # Note that Bundler's behaviour at this point actually conflicts with
    # it's own documentation here: http://bundler.io/v1.9/man/bundle-install.1.html#SUDO-USAGE
    export GEM_HOME="$(ruby -rubygems -e 'puts Gem.user_dir')"
fi

if [ -d $HOME/.rbenv/bin ]; then
    PATH="$PATH:$HOME/.rbenv/bin"
    eval "$(rbenv init -)"
fi

export PATH

alias e="emacsclient -nw -ca ''"
alias v="vim"
alias l="ls --color=auto"
alias ls="ls --color=auto"
alias ll="ls -l --color=auto"
alias la="ls -la --color=auto"
alias t="tree -C"
alias ta="tree -aC"

# stuff for vagrant
export VAGRANT_DEFAULT_PROVIDER=libvirt

# TODO: set up things for default perl local::lib, etc.

export VISUAL=vim

[ -x $HOME/.zshrc.local ] && source $HOME/.zshrc.local

if [ -r /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
