# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
unsetopt beep notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/zebdeos/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

zstyle ':completion:*' menu select
autoload -U colors && colors
#autoload -U promptinit && promptinit && prompt redhat
precmd() {
    local currtime
    currtime=$(date +'%Y-%m-%d %H:%M')
    PROMPT="%{$fg_bold[blue]%}[%n@%m%{$reset_color%} %{$fg_bold[green]%}%1~%{$reset_color%}%{$fg_bold[blue]%}]%(#.#.$)%{$reset_color%} "
    RPROMPT="%{$fg_no_bold[blue]%}($currtime)%{$reset_color%}"
}

# for the likes of gnome-terminal and mate-terminal
[ "x$TERM" = "xxterm" ] && export TERM="xterm-256color"

PATH="$PATH:$HOME/bin:$HOME/local/bin"

# per http://guides.rubygems.org/faqs/#user-install
if which ruby 1>/dev/null 2>&1 && which gem 1>/dev/null 2>&1; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

if [ -d $HOME/.rbenv/bin ]; then
    PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

export PATH

alias e="emacs -nw"
#alias e="emacsclient -nw -ca ''"
alias v="vim"
#alias ls="ls --color=auto"
alias l="ls --color=auto"
alias ls="ls --color=auto"
alias ll="ls -l --color=auto"
alias la="ls -la --color=auto"
alias t="tree -C"
alias ta="tree -aC"

# stuff for vagrant
export VAGRANT_DEFAULT_PROVIDER=libvirt

# stuff for python pip
export PIP_DOWNLOAD_CACHE="$HOME/ext/package/pip-cache"

# TODO: set up things for default perl local::lib, etc.

export VISUAL=vim

[ -x $HOME/.zshrc.local ] && source $HOME/.zshrc.local

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
