[Desktop Entry]
Name=Numix Custom
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Numix
MetacityTheme=Numix
IconTheme=matefaenzadark
GtkColorScheme=fg_color:#555555555555,bg_color:#dededededede,text_color:#333333333333,base_color:#f9f9f9f9f9f9,selected_fg_color:#f9f9f9f9f9f9,selected_bg_color:#373789d8d6d6,tooltip_fg_color:#dededededede,tooltip_bg_color:#2d2d2d2d2d2d
CursorTheme=Adwaita
CursorSize=24
NotificationTheme=nodoka
