" let g:loaded_netrw = 1
" let g:loaded_netrwPlugin = 1
let g:loaded_matchparen = 1
let g:netrw_list_hide= '\(^\|\s\s\)\zs\.[^\.]\S\+,\~$,^\.\/$,\.pyc$'
let g:netrw_banner=0

" disable alternate screen for vim
" http://shallowsky.com/linux/noaltscreen.html
set t_ti= t_te=

let g:pathogen_disabled = [
			\"calendar-vim",
			\"nerdtree",
			\"NrrwRgn",
			\"sparkup",
			\"syntastic",
			\"SyntaxRange",
			\"tagbar",
			\"UltiSnips",
			\"utl.vim",
			\"vim-fugitive",
			\"vim-misc",
			\"vim-notes",
			\"vim-orgmode",
			\"vim-snippets",
			\"vim-speeddating",
			\]
			" \"ack.vim",
			" \"powerline",
			" \"vim-coffee-script",
			" \"vim-easymotion",
			" \"vim-fugitive",
			" \"vim-javascript-syntax",
			" \"vim-repeat",
			" \"vim-sensible",
			" \"vim-sleuth",
			" \"vimux",
			" \"wombat256.vim",
			" \"zombat256.vim",
execute pathogen#infect()
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
let g:notes_directories = ['~/notes/vim-notes']
let g:NERDTreeMinimalUI=1
let g:NERDTreeWinSize = 25
let g:tagbar_width = 25
let g:syntastic_python_checkers = ['python', 'pep8', 'pyflakes']
set backupdir=~/local/tmp
set directory=~/local/tmp
set backup

set t_Co=256
set mouse=a
set ttymouse=xterm2
set background=dark
colorscheme zombat256

" http://stevelosh.com/blog/2010/09/coming-home-to-vim/#aesthetics
set list
set listchars=tab:▸\ ,eol:¬
set nowrap
set textwidth=0
set colorcolumn=72
set nocursorline
set nocursorcolumn
set nocompatible
set hlsearch
set vb t_vb= "no bell or visual bell
set clipboard+=unnamed
set noshowmode

" allow to switch away from unsaved buffers without saving OR
" discarding changes
set hidden

" http://www.guyrutenberg.com/2013/09/23/quickly-exiting-insert-mode-in-vim/
inoremap kj <ESC>
inoremap ,w <ESC>:w<Enter>
nmap ; :
let mapleader = ","
map <Leader>w :w<Enter>
" http://vim.wikia.com/wiki/Display_line_numbers
map <Leader>n :set invrelativenumber<Enter>
map <Leader>m :set invcursorline invcursorcolumn<Enter>
" TODO: Write function to rotate amongst 72, 80, and 0 colorcolumn
" map <Leader>t :NERDTreeToggle<Enter>
" map <Leader>g :Tagbar<Enter>

" https://raw.githubusercontent.com/benmills/vimux/master/doc/vimux.txt
map <Leader>vp :VimuxPromptCommand<CR>
map <Leader>vl :VimuxRunLastCommand<CR>
map <Leader>vi :VimuxInspectRunner<CR>
map <Leader>vq :VimuxCloseRunner<CR>
map <Leader>vx :VimuxInterruptRunner<CR>
map <Leader>vc :VimuxClearRunnerHistory<CR>
map <Leader>vz :VimuxZoomRunner<CR>
