#!/bin/sh

# Flatten and merge package list text files as formatted by me

g_packages=""
g_groups=""
g_aur=""
g_custom=""

# Loop through files passed as args
for list in "$@"; do
  # Filter out package names
  g_packages="$g_packages $(grep -v '\(^#\|^$\|^group:\|^aur:\|^custom:\)' $list)"

  # Filter out group names
  g_groups="$g_groups $(grep -v '\(^#\|^$\)' $list | grep '^group:' | sed 's/^group://')"

  # Filter out aur names
  g_aur="$g_aur $(grep -v '\(^#\|^$\)' $list | grep '^aur:' | sed 's/^aur://')"

  # Filter out custom names
  g_custom="$g_custom $(grep -v '\(^#\|^$\)' $list | grep '^custom:' | sed 's/^custom://')"
done

# Echo flatted package list, each package separated by whitespace
echo PACKAGES: $(echo $g_packages)
echo GROUPS: $(echo $g_groups)
echo AUR: $(echo $g_aur)
echo CUSTOM: $(echo $g_custom)
